# Generated by Django 5.2.1 on 2025-10-17 04:53

import apps.dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(choices=[('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Perú', 'Perú'), ('Brasil', 'Brasil'), ('Colombia', 'Colombia'), ('Uruguay', 'Uruguay')], max_length=30)),
                ('tipo', models.CharField(choices=[('Emisiones', 'Emisiones'), ('Energía', 'Energía'), ('Residuos', 'Residuos'), ('Transporte', 'Transporte'), ('Otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_revision', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.dashboard.models.upload_to_normativas)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Incumplimiento', 'Incumplimiento normativo'), ('Desviación', 'Desviación de meta'), ('Error', 'Error de carga o validación')], max_length=30)),
                ('mensaje', models.TextField()),
                ('severidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('resuelta', models.BooleanField(default=False)),
                ('visible_para', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='CargaConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carga', models.CharField(choices=[('Manual', 'Manual'), ('Masiva', 'Masiva')], max_length=20)),
                ('archivo', models.FileField(upload_to=apps.dashboard.models.upload_to_consumos)),
                ('validado', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('unidad_negocio', models.CharField(max_length=100)),
                ('fuente', models.CharField(max_length=100)),
                ('alcance', models.CharField(choices=[('1', 'Alcance 1 - Directas'), ('2', 'Alcance 2 - Indirectas (energía)'), ('3', 'Alcance 3 - Otras indirectas')], max_length=1)),
                ('consumo', models.FloatField(help_text='Cantidad consumida')),
                ('unidad', models.CharField(default='kWh', max_length=20)),
                ('factor_emision', models.FloatField(help_text='Factor en tCO₂e / unidad')),
                ('emisiones', models.FloatField(blank=True, help_text='Resultado tCO₂e', null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=apps.dashboard.models.upload_to_emisiones)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('Energía', 'Energía'), ('Transporte', 'Transporte'), ('Residuos', 'Residuos'), ('Otro', 'Otro')], max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('capex', models.FloatField(blank=True, help_text='Costo inicial USD', null=True)),
                ('opex', models.FloatField(blank=True, help_text='Costo anual USD', null=True)),
                ('reduccion_esperada', models.FloatField(blank=True, help_text='tCO₂e evitadas', null=True)),
                ('avance', models.FloatField(default=0, help_text='Porcentaje completado')),
                ('descripcion', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.dashboard.models.upload_to_iniciativas)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_negocio', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.dashboard.models.upload_to_reportes)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Energetica', 'Transición Energética'), ('Normativa', 'Normativas Legales')], max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
