# Generated by Django 5.2.1 on 2025-11-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='reduccion_real',
            field=models.FloatField(default=0, help_text='tCO₂e reales'),
        ),
    ]
