# Generated by Django 5.2.1 on 2025-10-24 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20251024_0007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emision',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RemoveField(
            model_name='emision',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='emision',
            name='emisiones',
        ),
        migrations.RemoveField(
            model_name='emision',
            name='factor_emision',
        ),
        migrations.RemoveField(
            model_name='emision',
            name='unidad',
        ),
        migrations.AddField(
            model_name='emision',
            name='consumo_cantidad',
            field=models.DecimalField(decimal_places=4, default='L', max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emision',
            name='consumo_tipo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emision',
            name='consumo_unidad',
            field=models.CharField(default='L', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emision',
            name='emisiones_tco2e',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='emision',
            name='factor_tco2e_por_unidad',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emision',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emision',
            name='pais',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('PE', 'Peru'), ('BR', 'Brasil'), ('CO', 'Colombia'), ('UY', 'Uruguay')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emision',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('Incumplimiento', 'Incumplimiento normativo'), ('Desviacion', 'Desviacion de meta'), ('Error', 'Error de carga o validacion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emision',
            name='alcance',
            field=models.CharField(choices=[('1', 'Alcance 1 - Directas'), ('2', 'Alcance 2 - Indirectas (energia)'), ('3', 'Alcance 3 - Otras indirectas')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emision',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emision',
            name='fuente',
            field=models.CharField(choices=[('combustible', 'Combustible'), ('electricidad', 'Electricidad'), ('refrigerantes', 'Refrigerantes'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emision',
            name='unidad_negocio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='categoria',
            field=models.CharField(choices=[('Energia', 'Energia'), ('Transporte', 'Transporte'), ('Residuos', 'Residuos'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='reduccion_esperada',
            field=models.FloatField(blank=True, help_text='tCO2e evitadas', null=True),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='pais',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('PE', 'Peru'), ('BR', 'Brasil'), ('CO', 'Colombia'), ('UY', 'Uruguay')], max_length=2),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='tipo',
            field=models.CharField(choices=[('Emisiones', 'Emisiones'), ('Energia', 'Energia'), ('Residuos', 'Residuos'), ('Transporte', 'Transporte'), ('Otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='tipo',
            field=models.CharField(choices=[('Energetica', 'Transicion Energetica'), ('Normativa', 'Normativas Legales')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='emision',
            index=models.Index(fields=['fecha'], name='dashboard_e_fecha_7ff7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='emision',
            index=models.Index(fields=['pais', 'fecha'], name='dashboard_e_pais_2bf285_idx'),
        ),
        migrations.AddIndex(
            model_name='emision',
            index=models.Index(fields=['alcance', 'fecha'], name='dashboard_e_alcance_1ec0be_idx'),
        ),
        migrations.AddIndex(
            model_name='emision',
            index=models.Index(fields=['fuente', 'fecha'], name='dashboard_e_fuente_8382ad_idx'),
        ),
    ]
