# Generated by Django 5.2.1 on 2025-10-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_emision_options_remove_emision_consumo_and_more'),
    ]

    operations = [
    ]
